title: "Öko-Feldtage: NO<sub>3</sub>"
favicon: images/favicon.ico
database:
  filename: nitrate.sqlite
  tablename: entries
  fields:
    - name: lat
      type: float
      description: Grad geogr. Breite
      notnull: true
    - name: lon
      type: float
      description: Grad geogr. Länge
      notnull: true
    - name: time
      type: datetime
      description: Datum / Uhrzeit
      notnull: true
    - name: samplename
      type: str
      description: Probenbezeichnung
      notnull: true
    - name: nitrate
      type: float
      description: Konzentration von NO3-N in mg/l
    - name: watersource
      type: str
      description: Art des Gewässers
      options:
        - Fluss / Bach
        - See / Teich
        - Quelle
        - Grundwasser
        - Leitungswasser
    - name: landuse
      type: str
      description: Landnutzung
      options:
        - Acker
        - Grünland
        - Nadelwald
        - Laubwald
        - Mischwald

    - name: comment
      type: str
      description: Weitere Bemerkungen

content:
  index:
    title: '&#x2302;'
    text: main.md
  about:
    title: Impressum
    text: about.md
map:
  title: Karte
  lon: 51.1
  lat: 9.8
  zoomlevel: 6
  location_btn: Standort ermitteln
  location_msg:
    show_precision: 1
    first_line: Da bist du!
    second_line_pt1: Erstelle
    second_line_pt2: einen Eintrag.
    link_string: hier
  access_token: pk.eyJ1IjoicGhpbGlwcGtyYWZ0IiwiYSI6ImNreXNqY3FyZjBuNm4yb3FhM2VmcjdxbXAifQ._zY1PN80gUpqEPe_3ZnYrA

SECRET_KEY: xy7PDi1XqBHtvYnnFB4xqTsPg0SOO5VrnSGIYEPr