database:
  filename: data/entries.sqlite
  tablename: entries
  fields:
    - name: lat
      type: float
      description: Grad geogr. Breite
    - name: lon
      type: float
      description: Grad geogr. Länge
    - name: length
      type: float
      description: Länge des Risses in cm
    - name: width
      type: float
      description: Breite des Risses in cm
    - name: depth
      type: float
      description: Tiefe des Risses in cm
    - name: landuse
      type: str
      description: Landnutzung
      options:
        - Acker
        - Grünland
        - Nadelwald
        - Laubwald
        - Mischwald
    - name: comment
      type: str
      description: Weitere Bemerkungen

content:
    main: main.md
    about: main.md

map:
  longitude: 51.1
  latitude: 9.8
  zoomlevel: 6