title: "Öko-Feldtage: NO<sub>3</sub>"
favicon: images/favicon.ico
database:
  filename: data/entries.sqlite
  tablename: entries
  fields:
    - name: lat
      type: float
      description: Grad geogr. Breite
    - name: lon
      type: float
      description: Grad geogr. Länge
    - name: length
      type: float
      description: Länge des Risses in cm
    - name: width
      type: float
      description: Breite des Risses in cm
    - name: depth
      type: float
      description: Tiefe des Risses in cm
    - name: landuse
      type: str
      description: Landnutzung
      options:
        - Acker
        - Grünland
        - Nadelwald
        - Laubwald
        - Mischwald
    - name: comment
      type: str
      description: Weitere Bemerkungen

content:
  index:
    title: '&#x2302;'
    text: main.md
  about:
    title: Impressum
    text: about.md
map:
  title: Karte
  longitude: 51.1
  latitude: 9.8
  zoomlevel: 6
  location_btn: Standort ermitteln
  location_msg:
    show_precision: 1
    first_line: Da bist du!
    second_line_pt1: Erstelle
    second_line_pt2: einen Eintrag.
    link_string: hier
  access_token: pk.eyJ1IjoicGhpbGlwcGtyYWZ0IiwiYSI6ImNreXNqY3FyZjBuNm4yb3FhM2VmcjdxbXAifQ._zY1PN80gUpqEPe_3ZnYrA